Support more linux paths and shorter rect64 values. Ignore multiple backuphash values.
Philipp91/picasa2digikam pull request #8
Opened 2022-05-26 18:26 UTC by athwds

2022-05-26 20:51 UTC, Philipp91 requested changes
Thank you! I can't test this myself but I trust you that it works. I only have some style-related comments.

Also, all files seem to be touched with `100644 → 100755`, i.e. making them executable. Do you know why this happened? Can you somehow undo it? (If not, I will do so before merging.)
If you use Windows, the Internet recommends setting the `core.filemode` option to false to prevent this in future commits.

2022-05-26 20:51 UTC, Philipp91 commented on digikam_db.py
> +            else:
Please make this also elif, and then
```
else:
  raise ValueError('Unsupported ...' % identifier)
```

2022-05-26 20:51 UTC, Philipp91 commented on rect64.py
> +    logging.info ("data=",data)
Please no space before `(`, but a space after `,`.

2022-05-26 20:51 UTC, Philipp91 commented on digikam_db.py
> +        logging.info("file=",file)
Please add a space after the `,`

2022-05-27 14:51 UTC, athwds commented
i will clean up code and create a new pull request

2022-05-27 14:51 UTC, closed without merging